# fly.toml app configuration file generated for puritytest on 2025-08-07T21:00:52-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'puritytest'
primary_region = 'lhr'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[mounts]
source = "data"
destination = "/app/purity-tests"

[[vm]]
size = 'shared-cpu-1x'
